matrix:
  fast_finish: true

install:

  # Download, extract, and build GEOS.
  - ps: (new-object net.webclient).DownloadFile('http://download.osgeo.org/geos/geos-3.5.0.tar.bz2', 'c:/projects/shapely/geos-3.5.0.tar.bz2')
  - cmd: 7z x c:/projects/shapely/geos-3.5.0.tar.bz2
  # - cmd: 7z x c:/projects/shapely/geos-3.5.0.tar -oc:/projects/shapely/geos-3.5.0_msvc1500_32
  # - cmd: 7z x c:/projects/shapely/geos-3.5.0.tar -oc:/projects/shapely/geos-3.5.0_msvc1500_64
  - cmd: 7z x c:/projects/shapely/geos-3.5.0.tar -oc:/projects/shapely/geos-3.5.0_msvc1600_32
  - cmd: 7z x c:/projects/shapely/geos-3.5.0.tar -oc:/projects/shapely/geos-3.5.0_msvc1600_64

  - cmd: set ORIGPATH=%PATH%
  # - cmd: 'set PATH=%PATH%;"C:\Users\appveyor\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0"'
  # - cmd: 'set PATH=%PATH%;"C:\Users\appveyor\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\bin"'

  # - cmd: cd c:/projects/shapely/geos-3.5.0_msvc1500_32/geos-3.5.0
  # - cmd: autogen.bat
  # - cmd: vcvarsall x86
  # - cmd: nmake makefile.vc MSVC_VER=1500

  # - cmd: cd c:/projects/shapely/geos-3.5.0_msvc1500_64/geos-3.5.0
  # - cmd: autogen.bat
  # - cmd: vcvarsall x86_amd64
  # - cmd: nmake makefile.vc MSVC_VER=1500

  - cmd: 'set PATH=%ORIGPATH%;C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC'
  - cmd: 'set PATH=%PATH%;C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin'

  - cmd: cd c:/projects/shapely/geos-3.5.0_msvc1600_32/geos-3.5.0
  - cmd: autogen.bat
  - cmd: 'echo "GEOS_MSVC = 10.0" >> nmake.opt'
  - cmd: 'echo "GEOS_MSC = 1600" >> nmake.opt'
  - cmd: vcvarsall x86
  - cmd: nmake /f makefile.vc

  - cmd: cd c:/projects/shapely/geos-3.5.0_msvc1600_64/geos-3.5.0
  - cmd: autogen.bat
  - cmd: 'echo "GEOS_MSVC = 10.0" >> nmake.opt'
  - cmd: 'echo "GEOS_MSC = 1600" >> nmake.opt'
  - cmd: vcvarsall x86_amd64
  - cmd: nmake /f makefile.vc
