matrix:
  fast_finish: true

install:

  # Download, extract, and build GEOS.
  - ps: (new-object net.webclient).DownloadFile('http://download.osgeo.org/geos/geos-3.5.0.tar.bz2', 'C:/projects/shapely/geos-3.5.0.tar.bz2')
  - cmd: 7z x C:/projects/shapely/geos-3.5.0.tar.bz2
  - cmd: 7z x C:/projects/shapely/geos-3.5.0.tar -oc:/projects/shapely/geos-3.5.0_msvc1900_32
  - cmd: 7z x C:/projects/shapely/geos-3.5.0.tar -oc:/projects/shapely/geos-3.5.0_msvc1900_64

  - cmd: set ORIGPATH=%PATH%
  # - cmd: 'set PATH=%PATH%;"C:\Users\appveyor\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0"'
  # - cmd: 'set PATH=%PATH%;"C:\Users\appveyor\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\bin"'

  - cmd: 'set PATH=%PATH%;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC'
  - cmd: 'set PATH=%PATH%;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin'

  # - cmd: cd c:/projects/shapely/geos-3.5.0_msvc1900_32/geos-3.5.0
  # - cmd: autogen.bat
  # - cmd: vcvarsall x86
  # - cmd: cd src
  # - cmd: nmake -f makefile.vc GEOS_MSVC=14.0 GEOS_MSC=1900

  - cmd: cd C:/projects/shapely/geos-3.5.0_msvc1900_64/geos-3.5.0
  - cmd: autogen.bat
  - cmd: vcvarsall x86_amd64
  - cmd: cd src
  - cmd: nmake -f makefile.vc GEOS_MSVC=14.0 GEOS_MSC=1900

  - cmd: cd C:/projects/shapely
  - cmd: 'mkdir shapely\DLLs'
  - cmd: cp C:/projects/shapely/geos-3.5.0_msvc1900_64/src/*.dll C:/projects/shapely/shapely/DLLs
  - cmd: C:/Python35-x64/python.exe setup.py build
